CREATE TABLE PUBLIC.ADDRESS (
  USER_ID INTEGER NOT NULL,
  STREET_NO VARCHAR_IGNORECASE(45),
  DETAIL_NO VARCHAR_IGNORECASE(45),
  CONSTRAINT ADDRESS_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_E ON PUBLIC.ADDRESS (USER_ID);

-- PUBLIC.ADDRESS foreign keys
ALTER TABLE PUBLIC.ADDRESS ADD CONSTRAINT ADDRESS_USERS_FK 
  FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) 
  ON DELETE CASCADE ON UPDATE CASCADE;