CREATE TABLE PUBLIC.ADDRESS (
  ID INTEGER NOT NULL,
  STREET_NO VARCHAR_IGNORECASE(45),
  DETAIL_NO VARCHAR_IGNORECASE(45),
  CONSTRAINT ADDRESS_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_E ON PUBLIC.ADDRESS (ID);