-- PUBLIC.CART definition

-- Drop table

-- DROP TABLE PUBLIC.CART;

CREATE TABLE PUBLIC.CART (
  CUSTOMERID VARCHAR_IGNORECASE(20) NOT NULL,
  VISITSN INTEGER NOT NULL,
  CONSTRAINT CART_PK PRIMARY KEY (VISITSN,CUSTOMERID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_1 ON PUBLIC.CART (CUSTOMERID,VISITSN);


-- PUBLIC.BUYITEM definition

-- Drop table

-- DROP TABLE PUBLIC.BUYITEM;

CREATE TABLE PUBLIC.BUYITEM (
  ID BIGINT NOT NULL,
  VISITSN INTEGER,
  CUSTOMERID CHARACTER VARYING(20),
  CONSTRAINT BUYITEM_PK PRIMARY KEY (ID),
  CONSTRAINT BUYITEM_CART_FK FOREIGN KEY (VISITSN,CUSTOMERID) REFERENCES PUBLIC.CART(VISITSN,CUSTOMERID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX BUYITEM_CART_FK_INDEX_3 ON PUBLIC.BUYITEM (VISITSN,CUSTOMERID);
CREATE UNIQUE INDEX PRIMARY_KEY_3 ON PUBLIC.BUYITEM (ID);