-- PUBLIC.EMPLOYEE definition

-- Drop table

-- DROP TABLE PUBLIC.EMPLOYEE;

CREATE TABLE PUBLIC.EMPLOYEE (
  ID INTEGER NOT NULL,
  ENAME VARCHAR_IGNORECASE(45),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC.EMPLOYEE (ID);


-- PUBLIC.EMAIL definition

-- Drop table

-- DROP TABLE PUBLIC.EMAIL;

CREATE TABLE PUBLIC.EMAIL (
  ID BIGINT NOT NULL,
  EMPLOYEE_ID BIGINT,
  CONSTRAINT EMAIL_PK PRIMARY KEY (ID),
  CONSTRAINT EMAIL_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES PUBLIC.EMPLOYEE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX EMAIL_EMPLOYEE_FK_INDEX_3 ON PUBLIC.EMAIL (EMPLOYEE_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_3F ON PUBLIC.EMAIL (ID);