-- PUBLIC.WORKSTATION definition

-- Drop table

-- DROP TABLE PUBLIC.WORKSTATION;

CREATE TABLE PUBLIC.WORKSTATION (
  ID INTEGER NOT NULL,
  WS_NUMBER INTEGER,
  FLOOR VARCHAR_IGNORECASE(45),
  CONSTRAINT WORKSTATION_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_A ON PUBLIC.WORKSTATION (ID);


-- PUBLIC.EMPLOYEE definition

-- Drop table

-- DROP TABLE PUBLIC.EMPLOYEE;

CREATE TABLE PUBLIC.EMPLOYEE (
  ID INTEGER NOT NULL,
  ENAME VARCHAR_IGNORECASE(45),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC.EMPLOYEE (ID);


-- PUBLIC.EMP_WS definition

-- Drop table

-- DROP TABLE PUBLIC.EMP_WS;

CREATE TABLE PUBLIC.EMP_WS (
  EMP_ID INTEGER NOT NULL,
  WS_ID INTEGER NOT NULL,
  CONSTRAINT EMP_WS_EMPLOYEE_FK FOREIGN KEY (EMP_ID) REFERENCES PUBLIC.EMPLOYEE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT EMP_WS_WORKSTATION_FK FOREIGN KEY (WS_ID) REFERENCES PUBLIC.WORKSTATION(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX EMP_WS_EMPLOYEE_FK_INDEX_7 ON PUBLIC.EMP_WS (EMP_ID);
CREATE INDEX EMP_WS_WORKSTATION_FK_INDEX_7 ON PUBLIC.EMP_WS (WS_ID);