-- PUBLIC.MANAGER definition

CREATE TABLE PUBLIC.MANAGER (
  ID BIGINT NOT NULL,
  CONSTRAINT MANAGER_PK PRIMARY KEY (ID)
);


-- PUBLIC.EMAIL definition

CREATE TABLE PUBLIC.EMAIL (
  ID BIGINT NOT NULL,
  MANAGER_ID BIGINT,
  CONSTRAINT EMAIL_PK PRIMARY KEY (ID),
  CONSTRAINT EMAIL_MANAGER_FK FOREIGN KEY (MANAGER_ID) REFERENCES PUBLIC.MANAGER(ID)
);