CREATE TABLE PUBLIC.USERS (
  ID INTEGER NOT NULL,
  USERNAME VARCHAR_IGNORECASE(45),
  ADDRESS_ID INTEGER,
  CONSTRAINT USERS_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.USERS (ID);

-- PUBLIC.USERS foreign keys

ALTER TABLE PUBLIC.USERS ADD CONSTRAINT USERS_ADDRESS_FK 
  FOREIGN KEY (ADDRESS_ID) REFERENCES PUBLIC.ADDRESS(ID) 
  ON DELETE CASCADE ON UPDATE CASCADE;